services:
    php:
        container_name: ${PHP_IMAGE:-php:8.0-cli-alpine}
        build:
            dockerfile: Dockerfile
            args:
                PHP_IMAGE: ${PHP_IMAGE:-php:8.0-cli-alpine}
        volumes:
            - '.:/var/www/html'
